apiVersion: batch/v1
kind: Job
metadata:
  name: newton
spec:
  template:
    spec:
      containers:
      - name: pi
        image: brittainhard/newton:0.0.1
      restartPolicy: Never
  backoffLimit: 4
