apiVersion: batch/v1
kind: Job
metadata:
  name: newton
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: root
        image: brittainhard/newton:0.0.1
        args: ["18"]
